[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ksha_csi_cc = "3J9w5Aof5M4CZtWCmQpEVAQTT1Z26AViYR8mxMnwvdq6"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
